import { Category } from './category';
import { Product } from './product';

// This is the same mock product data that is returned from the mockoon endpoint
export const PRODUCTS: Product[] = [
  {
    image: '../../assets/images/cropped/banana-puppy.jpg',
    thumb: '../../assets/images/thumbs/banana-puppy.jpg',
    title: 'Puppy Sized Banana Onesie',
    price: 24.99,
    description: 'This adorable banana themed onesie is the perfect fit for your little furry friend. Machine washable. One-size fits small animals under 10 lbs.',
    tags: ['puppy', 'onesie', 'banana', 'clothing'],
    category: Category.CLOTHES,
    id: 'banana-puppy',
  },
  {
    image: '../../assets/images/cropped/bird-in-straw-hat.jpg',
    thumb: '../../assets/images/thumbs/bird-in-straw-hat.jpg',
    title: 'Straw Party Hat for Parakeets',
    price: 12.99,
    description: 'This cute little purple, white, and green straw party hat will perfectly fit any parakeet sized bird. It is bio-degradable and non-toxic.',
    tags: ['bird', 'parakeet', 'hat', 'party', 'bio-degradable'],
    category: Category.HATS,
    id: 'bird-in-straw-hat',
  },
  {
    image: '../../assets/images/cropped/bowtie-dog.jpg',
    thumb: '../../assets/images/thumbs/bowtie-dog.jpg',
    title: 'Plaid Bowtie for Good Bois',
    price: 18.99,
    description: 'Is your doggo the goodest boi? Prove it by giving them this very dapper wool plaid bowtie. This will also work for very large cats.',
    tags: ['dog', 'bowtie', 'wool', 'very large cats', 'business attire'],
    category: Category.OTHER,
    id: 'bowtie-dog',
  },
  {
    image: '../../assets/images/cropped/bird-teacup-hat.jpg',
    thumb: '../../assets/images/thumbs/bird-teacup-hat.jpg',
    title: 'Teacup Hat for Parakeets',
    price: 8.99,
    description: 'Is this not just a regular teacup? Of course not, it is a bird sized tea cup that will perfectly fit any parakeet sized bird. It can also be used for bird tea parties.',
    tags: ['bird', 'parakeet', 'hat', 'party', 'teacup'],
    category: Category.HATS,
    id: 'bird-teacup-hat',
  },
  {
    image: '../../assets/images/cropped/cat-bonnet.jpg',
    thumb: '../../assets/images/thumbs/cat-bonnet.jpg',
    title: 'Baby Blue Baby Bonnet for Big Baby Kitties',
    price: 32.99,
    description: 'This beautiful egg shell blue baby bonnet is purrrfect for all of your bestest babies. This bonnet is hand knit by midwestern grandmas.',
    tags: ['cat', 'bonnet', 'hat', 'baby', 'knit'],
    category: Category.HATS,
    id: 'cat-bonnet',
  },
  {
    image: '../../assets/images/cropped/cat-costume.jpg',
    thumb: '../../assets/images/thumbs/cat-costume.jpg',
    title: 'Puss In Boots for Kitty',
    price: 53.99,
    description: 'This very fancy and totally era appropriate Puss In Boots themed outfit is just the thing to make your kitty stand out. ** Not responsible for murdered committed by angry cats **',
    tags: ['cat', 'outfit', 'costume', 'danger', 'adults-only'],
    category: Category.CLOTHES,
    id: 'cat-costume',
  },
  {
    image: '../../assets/images/cropped/cat-glasses-1.jpg',
    thumb: '../../assets/images/thumbs/cat-glasses-1.jpg',
    title: 'Dark Shades for Cool Cats',
    price: 12.99,
    description: 'Your cat\'s future is so bright they need to wear shades. Dark shades.',
    tags: ['cat', 'dude', 'cool', 'sunglasses'],
    category: Category.GLASSES,
    id: 'cat-glasses-1',
  },
  {
    image: '../../assets/images/cropped/cat-glasses-2.jpg',
    thumb: '../../assets/images/thumbs/cat-glasses-2.jpg',
    title: 'Round Shiny Sunglasses for Cats Only',
    price: 15.99,
    description: 'These sunglasses are only for cats. No dogs allowed. These glasses are too cool for dogs.',
    tags: ['cat', 'dude', 'cool', 'sunglasses'],
    category: Category.GLASSES,
    id: 'cat-glasses-2',
  },
  {
    image: '../../assets/images/cropped/cat-glasses-3.jpg',
    thumb: '../../assets/images/thumbs/cat-glasses-3.jpg',
    title: 'Morpheus Kitty Sunglasses',
    price: 18.99,
    description: 'Is this the Matrix? Or is your cat just way more interesting than you are? Probably both.',
    tags: ['cat', 'dude', 'cool', 'sunglasses'],
    category: Category.GLASSES,
    id: 'cat-glasses-3',
  },
  {
    image: '../../assets/images/cropped/chef-cat.jpg',
    thumb: '../../assets/images/thumbs/chef-cat.jpg',
    title: 'Professional Chef Hat for Cats',
    price: 19.99,
    description: 'Your cat just got their first job at the local bakery! Congratulations, they are going to need a hat.',
    tags: ['employed', 'cat', 'hat', 'chef', 'first job'],
    category: Category.HATS,
    id: 'chef-cat',
  },
  {
    image: '../../assets/images/cropped/cat-socks.jpg',
    thumb: '../../assets/images/thumbs/cat-socks.jpg',
    title: 'Tube Socks for Cats and Tiny Dogs',
    price: 9.99,
    description: 'Keep their little tootsies warm with these adorable 80s inspired tube socks. Pull them up for extra knee coverage.',
    tags: ['cat', 'tiny dog', 'socks', '80s', 'tube socks'],
    category: Category.OTHER,
    id: 'cat-socks',
  },
  {
    image: '../../assets/images/cropped/chicken-arms.jpg',
    thumb: '../../assets/images/thumbs/chicken-arms.jpg',
    title: 'Buff Arms for Chickens',
    price: 25.99,
    description: 'Are you tired of your chicken telling you they can\'t arm wrestle or lift heavy piles of logs? Well worry no more. These buff arms will make them look like a liar.',
    tags: ['chicken', 'buff', 'arms', 'get to work', 'fowl'],
    category: Category.OTHER,
    id: 'chicken-arms',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-2.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-2.jpg',
    title: 'Kurt Cobain Shades for Big Bois',
    price: 7.99,
    description: 'Your doggo is the biggest boi and also super grunge. These very cool Kurt Cobain inspired sunglasses will let everyone know how cool and aloof your dog is.',
    tags: ['dog', 'sunglasses', 'nirvana', 'grunge', 'alternative'],
    category: Category.GLASSES,
    id: 'dog-glasses-2',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-3.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-3.jpg',
    title: 'Harry Pupper Glasses',
    price: 10.99,
    description: 'You\'re a Wizard Pupper! and now you can have the round nerdy glasses to prove it.',
    tags: ['dog', 'glasses', 'nerd', 'wizard', 'brainy'],
    category: Category.GLASSES,
    id: 'dog-glasses-3',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-4.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-4.jpg',
    title: 'Mild Mannered Eager To Please Glasses For Doggos',
    price: 7.99,
    description: 'Your doggo just wants to make you happy. And nothing makes people happier than making their eager to please puppers wear glasses.',
    tags: ['dog', 'glasses', 'mild mannered', 'pupper', 'nerd'],
    category: Category.GLASSES,
    id: 'dog-glasses-4',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-5.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-5.jpg',
    title: 'Cool Dude reflective Shades for Weiner Dogs',
    price: 14.99,
    description: 'Their legs might be short but their cool is like four or five inches taller. These reflective shades look a lot cooler when they are reflecting palm trees.',
    tags: ['dog', 'sunglasses', 'reflective', 'cool', 'dude'],
    category: Category.GLASSES,
    id: 'dog-glasses-5',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-6.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-6.jpg',
    title: 'Intimidating Round Shades for Bulldogs',
    price: 18.99,
    description: 'These glasses are aggressively intimidating. Is he sleeping? Is he staring? You will never ever know.',
    tags: ['dog', 'sunglasses', 'dark', 'cool', 'scary'],
    category: Category.GLASSES,
    id: 'dog-glasses-6',
  },
  {
    image: '../../assets/images/cropped/dog-glasses-7.jpg',
    thumb: '../../assets/images/thumbs/dog-glasses-7.jpg',
    title: 'Professional Doggo Glasses',
    price: 18.99,
    description: 'Whether they are starting their first day in IT or they are writing their first novel. These very professional glasses will give your doggo the confidence they need to succeed!',
    tags: ['dog', 'glasses', 'successful', 'professional', 'Sys Admin'],
    category: Category.GLASSES,
    id: 'dog-glasses-7',
  },
  {
    image: '../../assets/images/cropped/glasses-pom.jpg',
    thumb: '../../assets/images/thumbs/glasses-pom.jpg',
    title: 'Office Glasses for Tiny Dogs',
    price: 14.99,
    description: 'Even toy breeds need to work, and what better way to look like you are fit for the job than to show up on your first day wearing glasses!',
    tags: ['dog', 'glasses', 'successful', 'professional', 'office work'],
    category: Category.GLASSES,
    id: 'glasses-pom',
  },
  {
    image: '../../assets/images/cropped/dog-yellow-boots.jpg',
    thumb: '../../assets/images/thumbs/dog-yellow-boots.jpg',
    title: 'Yellow Rubber Boots for Dogs',
    price: 23.99,
    description: 'Keep their little tootsies warm and dry with these bright yellow rain boots. Not suitable for humans',
    tags: ['dog', 'boots', 'rain', 'not for people', 'very yellow'],
    category: Category.OTHER,
    id: 'dog-yellow-boots',
  },
  {
    image: '../../assets/images/cropped/hoodie-bulldog.jpg',
    thumb: '../../assets/images/thumbs/hoodie-bulldog.jpg',
    title: 'Hoodie for Tough Babies',
    price: 31.99,
    description: 'No self respecting doggo would show up at the gym without this sweet Champion hoodie. Perfect for warm ups and cool downs.',
    tags: ['dog', 'hoodie', 'champion', 'gym rat', 'yellow'],
    category: Category.CLOTHES,
    id: 'hoodie-bulldog',
  },
  {
    image: '../../assets/images/cropped/jammie-cat.jpg',
    thumb: '../../assets/images/thumbs/jammie-cat.jpg',
    title: 'Kitty Baby Jam Jams',
    price: 11.99,
    description: 'Snuggle up on cold days with this sweet fleece pajama top. Bottoms optional and also not recommended. For cats or little dogs.',
    tags: ['cat', 'pajamas', 'fleece', 'warm up', 'small dogs'],
    category: Category.CLOTHES,
    id: 'jammie-cat',
  },
  {
    image: '../../assets/images/cropped/lamb-jams.jpg',
    thumb: '../../assets/images/thumbs/lamb-jams.jpg',
    title: 'Baaa Baaa Baby Jammies',
    price: 18.99,
    description: 'Wooly baby lambies need sweet soft jammies. Keep their little baby butts warm in these soft cotton flannel jam jams.',
    tags: ['flannel', 'pajama', 'sheep', 'lamb', 'cotton'],
    category: Category.CLOTHES,
    id: 'lamb-jams',
  },
  {
    image: '../../assets/images/cropped/overalls-puppy.jpg',
    thumb: '../../assets/images/thumbs/overalls-puppy.jpg',
    title: 'Denim Pooch Pants',
    price: 32.99,
    description: 'These rugged and durable overalls are great for little poochies who work hard and play harder! Now with 100% more pockets!',
    tags: ['dog', 'work pants', 'overalls', 'denim', 'small dogs'],
    category: Category.CLOTHES,
    id: 'overalls-puppy',
  },
  {
    image: '../../assets/images/cropped/paper-crown-cat.jpg',
    thumb: '../../assets/images/thumbs/paper-crown-cat.jpg',
    title: 'Fancy Paper Crown for Kitty',
    price: 1.99,
    description: 'This is literally made out of construction paper. Your cat is guaranteed to hate it.',
    tags: ['royalty', 'cat', 'paper', 'hat', 'crown'],
    category: Category.HATS,
    id: 'paper-crown-cat',
    onSale: true,
  },
  {
    image: '../../assets/images/cropped/parrot-suit.jpg',
    thumb: '../../assets/images/thumbs/parrot-suit.jpg',
    title: 'Bird Tuxedo',
    price: 65.99,
    description: 'Your parakeet got invited to a wedding but he hasn\'t a thing to wear! Do not worry my fine feathered friend, this very classic tuxedo is the perfect thing!',
    tags: ['bird', 'tuxedo', 'formal', 'wedding', 'bowtie'],
    category: Category.CLOTHES,
    id: 'parrot-suit',
  },
  {
    image: '../../assets/images/cropped/party-cat.jpg',
    thumb: '../../assets/images/thumbs/party-cat.jpg',
    title: 'Party Hat for Cat',
    price: 3.99,
    description: 'Nothing says party time like forcing your cat to wear a party hat! This party hat is made from cardboard and will totally annoy your cat for the entire three minutes they are wearing it.',
    tags: ['cat', 'party', 'hat', 'festive', 'annoying'],
    category: Category.HATS,
    id: 'party-cat',
  },
  {
    image: '../../assets/images/cropped/party-hat-cat.jpg',
    thumb: '../../assets/images/thumbs/party-hat-cat.jpg',
    title: 'Edible Party Hat for Cats',
    price: 5.99,
    description: 'What is the best way to celebrate your dog\'s birthday? Get the cat an edible party hat! Yummers!',
    tags: ['cat', 'party', 'hat', 'edible', 'dogs'],
    category: Category.HATS,
    id: 'party-hat-cat',
  },
  {
    image: '../../assets/images/cropped/pig-dress.jpg',
    thumb: '../../assets/images/thumbs/pig-dress.jpg',
    title: 'Fairy Dress for Piggies',
    price: 31.99,
    description: 'Hot pink tulle and polka dots will make any sweet piggy ready to party. Break out this lipstick and turn on the tunes!',
    tags: ['pig', 'dress', 'fairy', 'party', 'piggy'],
    category: Category.CLOTHES,
    id: 'pig-dress',
  },
  {
    image: '../../assets/images/cropped/pig-in-hat.jpg',
    thumb: '../../assets/images/thumbs/pig-in-hat.jpg',
    title: 'Cowboy Piggy Hat',
    price: 11.99,
    description: 'Get along little piggy! That\'s what people are going to say when they see your pig wearing this cute little cowboy hat and bandana.',
    tags: ['pig', 'cowboy', 'western', 'bandana', 'piggy'],
    category: Category.CLOTHES,
    id: 'pig-in-hat',
  },
  {
    image: '../../assets/images/cropped/pig-in-skates.jpg',
    thumb: '../../assets/images/thumbs/pig-in-skates.jpg',
    title: 'Pig Skates',
    price: 43.99,
    description: 'What could be cuter than a little pink piggy roller skating around the barnyard. These pink skates can handle any rough terrain and will last for years!',
    tags: ['pig', 'skates', 'roller skates', 'durable', 'pink'],
    category: Category.OTHER,
    id: 'pig-in-skates',
  },
  {
    image: '../../assets/images/cropped/pig-wig.jpg',
    thumb: '../../assets/images/thumbs/pig-wig.jpg',
    title: 'Pig Wig',
    price: 21.99,
    description: 'No more embarrassing bald piggies in your house! This very fancy wig is made from real acrylic and can withstand ever the most vigorous mud bath.',
    tags: ['pig', 'wig', 'acrylic', 'fancy', 'piggy'],
    category: Category.OTHER,
    id: 'pig-wig',
  },
  {
    image: '../../assets/images/cropped/pink-crown-cat.jpg',
    thumb: '../../assets/images/thumbs/pink-crown-cat.jpg',
    title: 'Paper Kitty Crown',
    price: 1.99,
    description: 'Yes. It is another paper crown for cats made out of construction paper. But this time it is pink. They will still hate it.',
    tags: ['cat', 'crown', 'paper', 'pink', 'party'],
    category: Category.HATS,
    id: 'pink-crown-cat',
  },
  {
    image: '../../assets/images/cropped/princess-piggy.jpg',
    thumb: '../../assets/images/thumbs/princess-piggy.jpg',
    title: 'Piggy Princess',
    price: 11.99,
    description: 'Every little piggy is a princess! And you can make your little piggy feel like royalty with this little crown.',
    tags: ['piggy', 'crown', 'paper', 'royalty', 'party'],
    category: Category.HATS,
    id: 'princess-piggy',
  },
  {
    image: '../../assets/images/cropped/pug-booties.jpg',
    thumb: '../../assets/images/thumbs/pug-booties.jpg',
    title: 'Pug Uggs',
    price: 19.99,
    description: 'Pug Uggs. For your dog\'s feet. These ones are black.',
    tags: ['dog', 'uggs', 'boots', 'black', 'cold'],
    category: Category.OTHER,
    id: 'pug-booties',
  },
  {
    image: '../../assets/images/cropped/red-hat-cat.jpg',
    thumb: '../../assets/images/thumbs/red-hat-cat.jpg',
    title: 'Red Party Hat for Cat',
    price: 3.99,
    description: 'This party hat is red to match the level of anger your cat will feel inside when you make them wear this thing.',
    tags: ['cat', 'party', 'hat', 'festive', 'annoying'],
    category: Category.HATS,
    id: 'red-hat-cat',
  },
  {
    image: '../../assets/images/cropped/st-paddy-pig.jpg',
    thumb: '../../assets/images/thumbs/st-paddy-pig.jpg',
    title: 'Saint Patrick Pig Sunglassed',
    price: 18.99,
    description: 'Kiss your pig! They are Irish! You can tell this pig is Irish because they are wearing green things and shamrock sunglasses.',
    tags: ['piggy', 'sunglasses', 'irish', 'leprechaun', 'party'],
    category: Category.GLASSES,
    id: 'st-paddy-pig',
  },
  {
    image: '../../assets/images/cropped/super-dog.jpg',
    thumb: '../../assets/images/thumbs/super-dog.jpg',
    title: 'Hero Dog Daily Wear',
    price: 19.99,
    description: 'Your dog is ready to be the hero, but they are going to need a cape. This sleek little number fits nicely under any office wear and is comfortable enough to wear all day!',
    tags: ['dog', 'hero', 'super', 'cape', 'costume'],
    category: Category.CLOTHES,
    id: 'super-dog',
  },
  {
    image: '../../assets/images/cropped/sweater-cat.jpg',
    thumb: '../../assets/images/thumbs/sweater-cat.jpg',
    title: 'Red Sweater for Kitty',
    price: 13.99,
    description: 'Keep kitty cozy all year round with this cute little red sweater. Roll up the sleeves to show everybody how cool your cat is.',
    tags: ['cat', 'sweater', 'winter', 'red', 'warm'],
    category: Category.CLOTHES,
    id: 'sweater-cat',
  },
];
